package com.motorola.contacts.util;

public class SpinnerIDGeneratorUtil  {

    private static final String TAG = "SpinnerIDGeneratorUtil";
    private static final int INITIAL_SPINNER_ID = 0xF0000;
    private static final int MAX_SPINNER_ID = 0xFFFFF;
    private static int mSpinnerID = INITIAL_SPINNER_ID; //default start value. Make sure the new id won't conflict with auto-generated ids and ids generated by ViewIdGenerator


    public static void resetSpinnerID() {
        mSpinnerID = INITIAL_SPINNER_ID;
    }

    public static int getSpinnerID() {
        if(mSpinnerID > MAX_SPINNER_ID){
            resetSpinnerID();
        }
        return mSpinnerID++; //return current value , then self ++
    }
}

